### ISSUE TITLE
一点小建议...

### ISSUE THREAD

**Issue by Lipraty** [initialencounter/mykoishi#1]
### 关于数据库方面建议：

https://github.com/initialencounter/mykoishi/blob/fae646daeea3240ed7d7d9b2cda559fc67e92516/blacklist/src/index.tsx#L13-L14

可以将 id 去除，以 uid 为主键，类似这样：

``` TypeScript
export interface Blacklist {
  uid: string
  violations: number //如果这是计数的话，可能叫 Count 会比较好？
  eula: boolean
}
//并且在下面的 model.extend 中这样注册：
ctx.model.extend('blacklist', {
    uid: 'unsigned',
    violations: 'integer(2)', //限制长度为 2 位，节省内存空间
    eula: 'boolean'
  }, {
    primary: 'uid', //设置 uid 为主键
    unique: ['uid'], //设置 uid 为唯一键
    foreign: {
      uid: ['user', 'id'] //将 uid 与 user 表的 id 绑定
    }
  })
```

### 一些可以优化的地方：

以代码复杂度来看，可以通过默认导出来使用 class 简化部分没必要的代码，默认导出的方式如下：

``` TypeScript
class Blacklist {
    public readonly name = 'blacklist'
    constructor(private ctx: Context, private config: Blacklist.Config){
        //your code
    }
    private async ban(uid: number, mix_auth:numbe) => {
      if (usr.id) {
        if (usr.authority < mix_auth) {
          await this.ctx.database.set('user', [usr.id], { authority: 0 })  //剥夺权限
          //         ^此处的 this.ctx 来自上边的 `constructor(private ctx`，这创建了一个内部变量
        }
      }
    }
}
namespace Blacklist {
    export interface Config = {...}
    export const Config: Schema.object({...})
}
export default Blacklist
```

https://github.com/initialencounter/mykoishi/blob/fae646daeea3240ed7d7d9b2cda559fc67e92516/blacklist/src/index.tsx#L60

中更加推荐使用 session.user.id，这是 koishi 内部的一个用户 id，而 session.userId 是仅针对平台用户的，比如在 onebot 平台中 userId 就是该用户的 qq 号。

https://github.com/initialencounter/mykoishi/blob/fae646daeea3240ed7d7d9b2cda559fc67e92516/blacklist/src/index.tsx#L140

由于我无法完全知道对于黑名单需求是在命令执行周期内还是全局（即所有聊天内容）生效，如果是仅命令执行周期内生效，可以将 message 事件更改为 command/before-execute ，例如：
``` TypeScript
ctx.before('command/execute', (argv: Argv)=>{
    //your code....
})
```

**Comment by initialencounter** [comment]
谢谢你!  Thank you!
