### ISSUE TITLE
屏蔽前缀失效

### ISSUE THREAD

**Issue by TatleCat** [initialencounter/mykoishi#11]
从前不久开始没法屏蔽前缀了或提示了
比如 me: dvc
bot: 我不明白您所说的"dvc"是什么,可以详细描述吗
而不是:你好,这里是猫猫伯特
或
me: dvc 你擅长什么
bot: 抱歉,我并不知道dvc是什么
而不是: 我善于解答所有人的疑惑

**Comment by initialencounter** [comment]
1.5.1有这个问题吗？

**Comment by TatleCat** [comment]
在私聊/群聊方面似乎解决了
但还有个细节上的问题
如:
在沙盒用户中输入dvc
回答是: 嗯?我没看到你说了什么,可以重述一遍吗?
而不是你已设定好的提示: 你好,这里是猫猫伯特...

还有的问题就是:
有些Bot账号会出现群聊无反应,无法调用指令
这种情况一般只能 @猫猫伯特 +指令
置顶/关闭免打扰等,都已试过了
最后是"风控",但只是部分长消息发不出去

**Comment by TatleCat** [comment]
此问题在最新版1.5.9重现
[当修好bug后出现另外一个bug (悲)]

**Comment by initialencounter** [comment]
1.5.9是什么问题，可以复现吗

**Comment by TatleCat** [comment]
![Screenshot_20230403_212316](https://user-images.githubusercontent.com/128877938/229522797-6681e6c4-fb8a-40a9-94df-40636adb09d2.jpg)
如图,不过第一个貌似在1.6.0解决了
但还有第二个问题在1.6.0未解决
不过使用上没什么影响(
