### ISSUE TITLE
关于dvc-003/代理/openai被停用

### ISSUE THREAD

**Issue by TatleCat** [initialencounter/mykoishi#14]
![Screenshot_20230402_060246](https://user-images.githubusercontent.com/128877938/229316214-98721af3-51cd-4828-9f87-7a7246d00110.jpg)
不知道最新的两个版本中
新添的代理功能 能否绕过IP限制
已经在申诉了

封禁邮件中提到
在不被openai支持的地区访问api会被封禁
其中可能包括内陆与港澳台

**Comment by initialencounter** [comment]
违反相关政策了，你的账号

**Comment by initialencounter** [comment]
最新版本已经可以自定义反代地址，可以绕过ip限制

**Comment by TatleCat** [comment]
> 最新版本已经可以自定义反代地址，可以绕过ip限制

同样无需额外配置吗(º﹃º )
