### ISSUE TITLE
会话过长自动重置后会将预设人格删除

### ISSUE THREAD

**Issue by YurikoSama** [initialencounter/mykoishi#18]
会话过长自动重置后会将预设人格删除，需要手动重置会话才恢复预设人格

**Comment by YurikoSama** [comment]
有办法解决吗？

**Comment by initialencounter** [comment]
最新版已经修复了吧

**Comment by YurikoSama** [comment]
> 最新版已经修复了吧

用的一直是3.1.1版本有这个BUG，自动重置会话后会清空人设，不过我改了配置文件中预设人格的内容，会是这个问题吗？
