### ISSUE TITLE
一点功能建议...

### ISSUE THREAD

**Issue by medicago087** [initialencounter/mykoishi#2]
关于steam-trading：
1. 建议增加一下筛选项，比如我只用buff倒余额，可以选择输入trad buff这样来获得一个筛选后的列表。
2. 我认为显示的参数项有些问题，网站默认排序使用的是"最优求购比例"，我认为挂刀获取余额的话"稳定求购比例"更有价值一些，而默认只显示的寄售比例我认为并无价值，单挂大件的话基本不会使用这个功能吧。当然，如果做成配置项也可以（

**Comment by initialencounter** [comment]
感谢建议! 已添加功能！
