### ISSUE TITLE
tencent-tts插件文字过长会报错

### ISSUE THREAD

**Issue by yi03** [initialencounter/mykoishi#20]
tencent-tts插件，如果想让它转长一些的文字，控制台会报 
`2023-06-03 12:32:28 [I] tencent-tts [TencentCloudSDKException]message:Text too long  requestId:3ea4e410-ecbd-4609-abfa-c91cad125485`
的错。
我看腾讯云的文档说基础语音合成最大支持150个汉字，实时语音合成最大支持600个汉字，长文本语音合成最多支持10万字符。不知道放不方便加个实时语音或长文本的选项。
或者超过150字了就分成多段合成。

**Comment by initialencounter** [comment]
感谢反馈，有时间会做
