### ISSUE TITLE
插件koishi-plugin-autoxjs-sender无法正常工作

### ISSUE THREAD

**Issue by fatinghenji** [initialencounter/mykoishi#23]
启用插件并按照readme配置后，能在手机端看到qq被正常唤醒，弹出发送对话框，但是并未发送消息。

https://github.com/initialencounter/mykoishi/assets/37131177/1e0e2911-c0eb-466a-a778-b2e518123974

观看录屏可以确认少点击了一个确认按键。请求更新js脚本。感谢！

**Comment by fatinghenji** [comment]
编辑：目前可以成功发送文字消息，但是无法发送图片。不清楚是怎么回事（

**Comment by initialencounter** [comment]
是文件夹的问题，你可能需要手动创建那个文件夹
