### ISSUE TITLE
关于人格设定

### ISSUE THREAD

**Issue by EDWARDCUIHUA** [initialencounter/mykoishi#25]
在添加人格并切换之后，再问问题或者自我介绍，ai并没有代入人格，是我操作有问题吗，大佬有没有人格设定方面的教学QWQ

**Comment by EDWARDCUIHUA** [comment]
欸，好像生效了，但是还是没太懂。

**Comment by EDWARDCUIHUA** [comment]
好吧并没有，我还是设定失败了qwq

**Comment by yunkuangao** [comment]
麻烦给一下相关的测试截图，比如人格设置，对话等，方便知道你的具体情况
