### ISSUE TITLE
在qq频道不能私聊

### ISSUE THREAD

**Issue by Dawn-Inator** [initialencounter/mykoishi#27]
老兄，貌似davinci在qq频道不能私聊啊
![_dc74a6a72729b343193e94107cb9fa9d_-245126098_Screenshot_20230818_162350](https://github.com/initialencounter/mykoishi/assets/126039858/2f245c06-574d-41e4-89f2-68205af322b1)
![_21bf3a4cbc8e3a24c1cc9488dcf067ba_502002391_Screenshot_20230818_162403](https://github.com/initialencounter/mykoishi/assets/126039858/3fb94d1c-8f73-423b-8d02-2af54d0a95ee)

**Comment by Dawn-Inator** [comment]
这是我私聊的日志
<img width="560" alt="chrome_1cpPIQml1Q" src="https://github.com/initialencounter/mykoishi/assets/126039858/9763ccd9-6086-496a-acbd-70d611dc42fe">

**Comment by Dawn-Inator** [comment]
![_1ee21f92ea9c234fd470d8b38a1e2d59_695473363_Screenshot_20230818_163730](https://github.com/initialencounter/mykoishi/assets/126039858/7d203a4d-e0b5-4a1e-bde9-b2f3f9b17c96)
日志里相应的对话

**Comment by initialencounter** [comment]
没用过频道机器人无法复现，有时间来远程一下，工作时间以外都可以
