### ISSUE TITLE
语音沙盒测试正常，QQ聊天报错

### ISSUE THREAD

**Issue by btwoa** [initialencounter/mykoishi#28]
tencent-tts报错，该如何解决，谢谢

<img width="430" alt="截屏2023-08-23 16 14 28" src="https://github.com/initialencounter/mykoishi/assets/109867618/bf96871c-98d0-4385-97cc-57360f92f90f">
<img width="1238" alt="截屏2023-08-23 16 17 37" src="https://github.com/initialencounter/mykoishi/assets/109867618/33c3f3b0-0d01-4fbc-a11e-9ebd3ff43303">

**Comment by initialencounter** [comment]
装了ffmpeg吗？

**Comment by initialencounter** [comment]
ffmpeg环境变量配了吗？终端输入ffmpeg看看输出

**Comment by btwoa** [comment]
没有配置，我是通过apk安装的

**Comment by btwoa** [comment]
参考的这篇教程
https://forum.koishi.xyz/t/topic/527
我该怎么配置

**Comment by btwoa** [comment]
复现了下，alpine镜像源问题，已成功启用，谢谢开发者耐心回复
