### ISSUE TITLE
Midjourney的参数不被适用

### ISSUE THREAD

**Issue by pk4ever1** [initialencounter/mykoishi#30]
**koishi-plugin-artwise中，关键词里加的参数被无视了。
如图，想设置图片比例为16:9。但出来的结果1:1。
知数云的api中，prompt里写入这种参数是有效的。**

![20231004064824](https://github.com/initialencounter/mykoishi/assets/54262354/7e48db08-efeb-4c43-a62d-f1e35ea24a5e)

**Comment by initialencounter** [comment]
知数云官方提供的接口没有这个可选参数
