### ISSUE TITLE
[enhancement]建议将type属性改为可配置

### ISSUE THREAD

**Issue by flymyd** [initialencounter/mykoishi#31]
有时我们可能需要请求特定版本的gpt模型，比如gpt-4-1106-preview、gpt-3.5-turbo-1106等。尤其对于使用中转api的用户来说，指定模型种类可以显著地降低使用成本。
建议将type属性改为可配置的选项，或增加一个新的选项以覆盖type。如：appointModel: 'gpt-4-1106-preview'，当存在此属性时type失效。

**Comment by initialencounter** [comment]
好的，有时间会做
