### ISSUE TITLE
考虑迁移到 boilerplate 建议的工作区仓库架构吗？

### ISSUE THREAD

**Issue by shigma** [initialencounter/mykoishi#32]
简单而言就是：

- 在你的本地重新建立一个新的 boilerplate，并将当前仓库放入 external 的一个子目录（或其他被 gitignore 的目录）
- 稍微修改 package.json

带来的好处是：

- 方便别人在模板项目中直接引入你的仓库

**Comment by initialencounter** [comment]
好嘞，我试试

**Comment by shigma** [comment]
> 这个仓库就是基于 boilerplate 开发的，可以直接引入吧，我试了一下，直接在 boilerplate 执行 yarn clone initialencounter/mykoishi，没问题呀

这样装的话会额外装你根工作区 package.json 里的依赖，应该是不需要的吧？

而且，目前这样得 build 才能启动，不能直接 dev。

**Comment by shigma** [comment]
啊，你没有理解迁移到 boilerplate 的意思 🤣 

https://koishi.chat/zh-CN/cookbook/design/workspace.html
