### ISSUE TITLE
群友の意见

### ISSUE THREAD

**Issue by Nijikaza** [initialencounter/mykoishi#38]
群友希望此插件可以实现裁剪图片，他提到
“help-pro之前是可以根据文本长度放大和裁剪图片的”，
“但是后来就不能了，表现为背景图片永远是原来的比例”，
![Screenshot_20240312_204626_com tencent mobileqq](https://github.com/initialencounter/mykoishi/assets/157272668/19f565b6-3b45-4421-93b2-b9426dcb9a27)
就是这样的

**Comment by initialencounter** [comment]
fix with [8018411](https://github.com/initialencounter/mykoishi/commit/80184111d64d765d431931d7c55ca2a1f68fc543)
