### ISSUE TITLE
在docker中运行的koishi里添加adapter-wechat4u插件会出现“插件加载失败”

### ISSUE THREAD

**Issue by erweixun** [initialencounter/mykoishi#40]
![image](https://github.com/initialencounter/mykoishi/assets/32983249/747b0971-3fb1-49a2-90a2-0db7c098caef)

输出日志：

![image](https://github.com/initialencounter/mykoishi/assets/32983249/24755a3f-d0e3-44ba-88ab-6554b9979326)

**Comment by initialencounter** [comment]
重装插件试试呢

**Comment by erweixun** [comment]
已解决，存粹是安装缓慢，过段时间查看发现加载完成了
