### ISSUE TITLE
sd-taylor 插件是否能添加修改出图延迟的功能

### ISSUE THREAD

**Issue by erweixun** [initialencounter/mykoishi#42]
在使用sd-taylor配合adapter-wechat4u时，经常出现not found错误；
经过几次测试，猜测是后端的SDwebUI还没画好，sd-taylor就去查询结果了；
于是进行测试，关闭高分辨率修复，降低图片分辨率，其他参数全部相同的情况下，用35步生成和用15步生成，结果验证确实如此：
![image](https://github.com/initialencounter/mykoishi/assets/32983249/7f12aefd-053e-4da7-b063-133485d0f94a)

**Comment by initialencounter** [comment]
可以把 SD 的 API 借我测试一些吗？

**Comment by erweixun** [comment]
大佬你能留个邮箱或者其他联系方式吗，我用其他方式发你

**Comment by initialencounter** [comment]
QQ 3118087750
