### ISSUE TITLE
adapter-wechat4u 重新登录问题

### ISSUE THREAD

**Issue by ktKongTong** [initialencounter/mykoishi#44]
感谢你的出色工作。

wechat4u 每次重新登录之后 bot的selfId，channelID，userId 均会发生变更，这对于需要DB以保存用户信息的的服务很不友好。这是预期之内的行为吗？如果不是，有什么办法可以规避吗？如果是，有什么办法可以唯一标识channel、user，使得重新登录后，之前存储的信息仍有效？

**Comment by initialencounter** [comment]
这是预期的哦，暂时没有解决方法，除非换轮子

**Comment by initialencounter** [comment]
> 感谢你的出色工作。
> 
> wechat4u 每次重新登录之后 bot的selfId，channelID，userId 均会发生变更，这对于需要DB以保存用户信息的的服务很不友好。这是预期之内的行为吗？如果不是，有什么办法可以规避吗？如果是，有什么办法可以唯一标识channel、user，使得重新登录后，之前存储的信息仍有效？

不过有一个不靠谱的方法，就是设置一个心跳，例如定时发送消息， 防止 wechat4u 退出登录

**Comment by cn1095** [comment]
请问这个最后是如何解决的呢？怎么设置心跳 有教程吗？会封号吗？
