### ISSUE TITLE
vocechat的适配器有的插件好像不起作用，请教下大佬是什么问题

### ISSUE THREAD

**Issue by libashanxi** [initialencounter/mykoishi#46]
比如有个比如有个插件是疯狂星期四，在vocechat中发送是有效果的
![3dd11bbfb03f94353a9c1508788a711](https://github.com/initialencounter/mykoishi/assets/65264574/e9cb6381-1141-44b8-998b-e23cd849f6bf)
还有个插件是每日新闻的，在vocechat中发送关键词是没有回复的，但是在koishi沙盒模式是OK的
![a163fb28f1a55fe82698109cd334a50](https://github.com/initialencounter/mykoishi/assets/65264574/3e75e85b-9d91-44c1-a44b-d27b7fe9356f)
![b955c9b90982790b8361e8066bb4890](https://github.com/initialencounter/mykoishi/assets/65264574/a300ed35-9a64-4641-808f-5ce10df69071)

**Comment by initialencounter** [comment]
这个新闻插件叫啥？我来测试一下

**Comment by libashanxi** [comment]
名称是这个
koishi-plugin-todaynews
不过我发现还有一些好像也没有作用，比如有个音乐的插件
koishi-plugin-music-downloadvoice-api
这个也是在沙盒里是有用的

**Comment by libashanxi** [comment]
我怀疑是我的问题，比如这个点歌的插件，我这边的日志如下：
2024/5/11 14:54:27                              at async Command.execute (/koishi/node_modules/@koishijs/core/lib/index.cjs:1163:22)
2024/5/11 14:54:27                              at async Array.<anonymous> (/koishi/node_modules/@koishijs/core/lib/index.cjs:1149:14)
2024/5/11 14:54:27                              at async Command.<anonymous> (/koishi/node_modules/koishi-plugin-music-downloadvoice-api/lib/index.js:178:25)
2024/5/11 14:54:27                              at async VoceBot.sendMessage (/koishi/node_modules/@satorijs/core/lib/index.cjs:323:22)
2024/5/11 14:54:27                              at async VoceMessenger.send (/koishi/node_modules/@satorijs/core/lib/index.cjs:564:5)
2024/5/11 14:54:27                              at async VoceMessenger.flush (/koishi/node_modules/koishi-plugin-adapter-voce/lib/message.js:36:19)
2024/5/11 14:54:27                              at async Internal.sendReplyMessage (/koishi/node_modules/koishi-plugin-adapter-voce/lib/adapter.js:237:19)
2024/5/11 14:54:27                              at async Proxy.<anonymous> (/koishi/node_modules/@cordisjs/plugin-http/lib/index.cjs:191:26)
2024/5/11 14:54:27                              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024/5/11 14:54:27                              at [cordis.invoke] (/koishi/node_modules/@cordisjs/plugin-http/lib/index.cjs:331:23)
2024/5/11 14:54:27  2024-05-11 14:54:27 [W] session Error: Bad Request
2024/5/11 14:54:26  2024-05-11 14:54:26 [I] Voce 机器人:[33m12544588[0m 收到消息: 发送者: [32m1[0m 内容: 点歌 朋友

**Comment by initialencounter** [comment]
> 我怀疑是我的问题

无法复现这个问题
![image](https://github.com/initialencounter/mykoishi/assets/109729945/6c7371a2-afb8-4217-b0fb-d6294509feed)

**Comment by initialencounter** [comment]
发送图片的bug已修，请更新到v1.0.1
