### ISSUE TITLE
提示不合规，检查违禁词，还有一个插件启用了但是没有提示成功

### ISSUE THREAD

**Issue by carry6667** [initialencounter/mykoishi#5]
![20230313000047](https://user-images.githubusercontent.com/127678041/224556885-bb8751b7-8e4e-40e0-bb5f-9c6f89d39a3b.png)
![20230313000214](https://user-images.githubusercontent.com/127678041/224556921-a4d69ebd-098f-4e62-801d-ce55b4b67099.png)

**Comment by initialencounter** [comment]
谢谢你!  Thank you!

**Comment by initialencounter** [comment]
已修复，请更新到1.4.5
