### ISSUE TITLE
adapter-voce: webhook path 如何填写

### ISSUE THREAD

**Issue by Neptune1990** [initialencounter/mykoishi#50]
path如何填写，目前填写的是Webhook 接收地址，报错app TypeError: Missing parameter name at 4
![image](https://github.com/initialencounter/mykoishi/assets/107494041/c13c3f20-964d-436d-898b-8afc0f97b9ac)
![image](https://github.com/initialencounter/mykoishi/assets/107494041/a091884c-80dc-4848-a773-33c3f000ba3f)

**Comment by initialencounter** [comment]
插件页面默认就好，vocechat后端填写 http://IP:端口/vocechat/webhook

例如我的 koishi webui 地址是 http://192.168.3.11:5140

那么我填写的就是 http://192.168.3.11:5140/vocechat/webhook

**Comment by Neptune1990** [comment]
已解决
