### ISSUE TITLE
helo-pro报错property database is not registered

### ISSUE THREAD

**Issue by lumia1998** [initialencounter/mykoishi#52]
Error: property database is not registered, declare it as `inject` to suppress this warning
![image](https://github.com/initialencounter/mykoishi/assets/63107956/67905652-94f1-4460-ba91-86851f402cdc)
![image](https://github.com/initialencounter/mykoishi/assets/63107956/c45d70ab-eb02-4d9e-a740-ec26c57db9bb)

**Comment by initialencounter** [comment]
已修复
