### ISSUE TITLE
davinci-003 更新到7.0.0之后引用回复失效

### ISSUE THREAD

**Issue by wahaha216** [initialencounter/mykoishi#56]
每次回复都有个 \<quote id="-2147443880"\/\>，其他插件引用回复是正常的，而且这个id每次还不一样，好像是根据消息数量递增
![PixPin_2024-08-15_11-02-59](https://github.com/user-attachments/assets/5c1ee0b6-7d3c-43f1-b349-75d72b52ed71)

**Comment by initialencounter** [comment]
这个是私聊吗

**Comment by initialencounter** [comment]
已修复 7.0.1
