### ISSUE TITLE
文字输出正常，语音输出报错

### ISSUE THREAD

**Issue by chqw163** [initialencounter/mykoishi#6]
![image](https://user-images.githubusercontent.com/43513937/225517834-70ead292-5da6-48f9-ba93-65312a6ce67a.png)
![image](https://user-images.githubusercontent.com/43513937/225518283-17a938a2-5922-48df-93ec-b70c7e33afb4.png)

如图，ai聊天正常
输出语音报错
另外rate-limit显示未加载，版本都是最新

**Comment by initialencounter** [comment]
这是正常的，api的问题，等会儿就好了
