### ISSUE TITLE
[Bug] 把选项指令当作提示词输入了

### ISSUE THREAD

**Issue by LingChen-tsjmdlc** [initialencounter/mykoishi#60]
![image](https://github.com/user-attachments/assets/df2a3411-e08a-419b-9685-a9b851f36c0b)

**Comment by initialencounter** [comment]
这是正常的，要把选项放在提示词前面

**Comment by furryaxw** [comment]
> 这是正常的，要把选项放在提示词前面

我在使用“tl txt”时插件将txt作为提示词输入了
![image](https://github.com/user-attachments/assets/865a4012-3805-4c32-b052-fc0bb4f386c0)
