### ISSUE TITLE
出现警告：[W] app Error: Parse Error: Invalid status code

### ISSUE THREAD

**Issue by xhit-ux** [initialencounter/mykoishi#61]
![image](https://github.com/user-attachments/assets/3003459a-7322-453b-86bc-63e84fa9529f)
出现后后续无法响应发送的消息，重启插件后恢复，
以及，，收到的消息无法发送到后台用chatluna配置的大模型处

**Comment by initialencounter** [comment]
谢谢你!  Thank you!

**Comment by initialencounter** [comment]
哪个插件

**Comment by xhit-ux** [comment]
adapter-wechat4u
koishi的插件，而且只能收到status着一个指令，其它指令和消息只要发送都会有这个报错，后续就只能重启插件才能正常运行

**Comment by initialencounter** [comment]
这是正常滴，上游的wechaty两年没更新了

**Comment by xhit-ux** [comment]
噢噢好的吧，谢谢啦
