### ISSUE TITLE
腾讯 sst 使用错误

### ISSUE THREAD

**Issue by dingyi222666** [initialencounter/mykoishi#64]
Koishi 新版本中 [部分消息元素的附件地址](https://koishi.chat/zh-CN/about/upgrade.html#%E6%B6%88%E6%81%AF%E5%85%83%E7%B4%A0%E6%9B%B4%E6%96%B0) 已从 `url` 更改为 `src`:

![7c15a1ee4ab4938ff359a082c9a25200](https://github.com/user-attachments/assets/7a8f6e91-2e73-48c9-8a48-0cf8befc1f5e)

当附件地址指向为本地文件时，腾讯 sst 时则会出现如下错误（即使修复了上面的更名问题）：

![image](https://github.com/user-attachments/assets/0d38c26c-6090-4ecb-af27-43d82528069b)

查阅文档可知，腾讯的语音文件识别支持上传本地音频文件（以 base64 编码）：

https://cloud.tencent.com/document/product/1093/37823

希望能适配此特性。当检测到音频地址不是公网地址时则上传本地文件。

**Comment by dingyi222666** [comment]
以及腾讯和百度都开放了一句话识别的语音转文件接口（60 秒以内），对于短音频可以调用这些接口，能做到快速返回。

主要是需要识别音频是否为短音频，可能需要其他库。

**Comment by initialencounter** [comment]
感谢反馈，正在迁移到`一句话识别`
