### ISSUE TITLE
davinci-003功能请求：接口报错提示

### ISSUE THREAD

**Issue by Astlvk** [initialencounter/mykoishi#8]
你好，这边目前尝试使用时，如果后台接口报错，那么在聊天界面是没有任何感知的，无法判断是还没响应还是报错。可以的话希望能追加相关功能以及功能开关。

**Comment by initialencounter** [comment]
是超级管理员没有回复吗，如果是请更新到1.4.8

**Comment by Astlvk** [comment]
> 是超级用户没有回复吗，如果是请更新到1.4.8

这边是接入的qq，后台接口报错的时候（控制台上打印的是invalid content或是axios error之类的错误），目前在qq聊天界面没有任何感知。

**Comment by Astlvk** [comment]
以下是目前观察到的一些报错：
1、davinci-003 AxiosError: Request failed with status code 400
2、davinci-003 TypeError: message.indexOf is not a function
3、
ChatGPT返回内容:
{
  msg: [
    {
      role: 'sys',
      content: 'TypeError: message.indexOf is not a function'
    }
  ],
  id: 1
}
session TypeError: Invalid content: [object Object]

**Comment by initialencounter** [comment]
1.6.0已经修复目前已发现的bug了
